# File: nixpacks.toml

[nixpacks.environment]
# Variabel untuk menunjuk ke file php.ini kustom Anda
NIXPACKS_PHP_INI_PATH = "php.ini"

# Variabel KHUSUS untuk mengatur batas upload NGINX
NIXPACKS_PHP_NGINX_CLIENT_MAX_BODY_SIZE = "64M"